apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-7ig304
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-7ig304
  namespace: my-nginx-7ig304
  labels:
    name: nginx-7ig304
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-7ig304
  template:
    metadata:
      namespace: my-nginx-7ig304
      labels:
        name: nginx-7ig304
    spec:
      containers:
      - name: nginx-7ig304
        image: nginx
        ports:
        - containerPort: 80

